version: '{build}'  

image: ubuntu

pull_requests:  
  do_not_increment_build_number: true

environment:
  AWS_ACCESS_KEY_ID:
    secure: V3KPdkkR+rRBPZJl/f/9MT5K9frQbzCzUAFCf/eBP0c=
  AWS_SECRET_ACCESS_KEY:
    secure: 55f2uQ/T0Us5NZ2aPpzeCyowt/tAynqsRmknW6cjvHUpqKI7RA4X9fQf4jEYaDeJ

services:
  - docker

install:
  - sh: sudo apt-get install unzip
  - sh: wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
  - sh: unzip terraform_0.11.10_linux_amd64.zip
  - sh: sudo mv terraform /usr/local/bin/
  - sh: terraform --version

build:
  verbosity: minimal

configuration: Release

build_script:  
  - ps: .\build.ps1

artifacts:
  - path: terraform.txt
    name: Terraform

skip_non_tags: true