version: '{build}'  

image: ubuntu

pull_requests:  
  do_not_increment_build_number: true

environment:
  AWS_ACCESS_KEY_ID:
    secure: V3KPdkkR+rRBPZJl/f/9MT5K9frQbzCzUAFCf/eBP0c=
  AWS_SECRET_ACCESS_KEY:
    secure: 55f2uQ/T0Us5NZ2aPpzeCyowt/tAynqsRmknW6cjvHUpqKI7RA4X9fQf4jEYaDeJ

services:
  - docker

install:
  - choco install terraform

build:
  verbosity: minimal

configuration: Release

build_script:  
  - ps: .\build.ps1

artifacts:
  - path: terraform.txt
    name: Terraform

skip_non_tags: true