version: 0.2

env:
  variables:
    TerraformSha256: "43543a0e56e31b0952ea3623521917e060f2718ab06fe2b2d506cfaa14d54527"
    TerraformSVersion: "0.11.10"

phases:
  install:
    commands:
      - echo Entered the install phase ...
      - echo Install Terraform ...
      - cd /tmp 
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/${TerraformSVersion}/terraform_${TerraformSVersion}_linux_amd64.zip
      - sha256sum --version
      - echo "${TerraformSha256}  terraform.zip" | sha256sum -c --quiet
      - unzip terraform.zip
      - mv terraform /usr/bin
      - cd ${CODEBUILD_SRC_DIR}
    finally:
      - echo End of install phase 
  pre_build:
    commands:
      - echo Entered the pre_build phase ...
      - echo Apply Infrastructure from Terraform ...
      - cd /bookystuff.Terraform
      - echo ... init ...
      - terraform init
      - echo Apply Infrastructure from Terraform ...
      - echo ... plan ...
      - terraform plan
      - echo Apply Infrastructure from Terraform ...
      - echo ... apply ...
      - terraform apply -auto-approve
      - cd ..
    finally:
      - echo End of pre_build phase
  build:
    commands:
      - echo Entered the build phase...
      - cd bookystuff.Server
      - echo ... build ...
      - docker build -t 322767926738.dkr.ecr.ap-southeast-2.amazonaws.com/bookystuff:bookystuff-blazor bookystuff.Server
      - echo ... login ...
      - $(aws ecr get-login --no-include-email --region $aws_region)
      - echo ... push ...
      - docker push 322767926738.dkr.ecr.ap-southeast-2.amazonaws.com/bookystuff:bookystuff-blazor
    finally:
      - echo End of build phase
